version: "3.6"
services:
  discovery:
    build: ./EurekaServer
    ports:
      - "3010:8755"
    image: "eureka-service"

  Conge:
    build: ./DemandeConge
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8755/eureka/
    ports:
      - "3003:8085"
    image: "conge-service"
    depends_on:
      - discovery

  gateway:
    build: ./API-Gateway_Server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8755/eureka/
    ports:
      - "3006:8090"
    image: "gateway-service"
    depends_on:
      - discovery

